"""Draw the application icon, once, into a committed .ico and .svg.

Run when the icon changes and commit the result. Deliberately not run at
install time: Pillow is not a declared dependency of this project, and an
icon is not something that needs generating on a user's machine.

    .venv/Scripts/python tools/make_icon.py

The shape has to survive 16 pixels, which is where it will actually be seen -
a taskbar button, a file listing, the corner of a window. That rules out
anything with fine detail, so this is two shapes: the brand's blue rounded
square, and a play triangle knocked out of it. Blue says which application,
the triangle says video, and both are still legible when the whole thing is
the size of a full stop.
"""

from __future__ import annotations

import argparse
from pathlib import Path

# The app's own colours, so the icon, the window chrome and the phone's home
# screen all agree.
BLUE = (77, 163, 255, 255)
DARK = (15, 18, 24, 255)

# Windows picks the nearest size and scales, so these are the ones it will
# actually reach for: 16 in a list, 32 on the desktop, 48 in the taskbar,
# 256 for the large view in Explorer.
SIZES = (16, 24, 32, 48, 64, 128, 256)

# Drawn at this multiple and scaled down, because Pillow's polygon and
# rounded-rectangle edges are hard otherwise, and hard edges at 16 pixels look
# like a mistake rather than a style.
SUPERSAMPLE = 8


def draw(size: int):
    from PIL import Image, ImageDraw

    big = size * SUPERSAMPLE
    image = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    canvas = ImageDraw.Draw(image)

    # A little breathing room, or the corners touch the edge of the tile and
    # the shape reads as a square rather than as an icon.
    pad = big * 0.06
    radius = big * 0.22
    canvas.rounded_rectangle(
        [pad, pad, big - pad, big - pad], radius=radius, fill=BLUE
    )

    # A play triangle, nudged right of centre so it looks centred - the
    # optical centre of a triangle is not its bounding box's.
    width = big * 0.30
    height = big * 0.34
    left = big / 2 - width * 0.38
    top = big / 2 - height / 2
    canvas.polygon(
        [(left, top), (left, top + height), (left + width, top + height / 2)],
        fill=DARK,
    )
    return image.resize((size, size), Image.LANCZOS)


SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" role="img"
     aria-label="TextSearchVDO">
  <!-- Generated by tools/make_icon.py - edit that, not this. -->
  <rect x="15" y="15" width="226" height="226" rx="56" fill="#4da3ff"/>
  <path d="M 99.5 84.5 L 99.5 171.5 L 176.3 128 Z" fill="#0f1218"/>
</svg>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("."))
    args = ap.parse_args()

    frames = [draw(size) for size in SIZES]

    ico = args.out / "TextSearchVDO.ico"
    frames[-1].save(ico, format="ICO", sizes=[(s, s) for s in SIZES])
    print(f"  {ico}  {ico.stat().st_size / 1024:.1f} KB  ({len(SIZES)} sizes)")

    png = args.out / "web" / "icon-512.png"
    png.parent.mkdir(parents=True, exist_ok=True)
    draw(512).save(png, format="PNG")
    print(f"  {png}  {png.stat().st_size / 1024:.1f} KB")

    svg = args.out / "web" / "icon.svg"
    svg.write_text(SVG, encoding="utf-8")
    print(f"  {svg}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
